spring: 
  application:
    name: item-service
  rabbitmq:
    host: 192.168.93.130
    port: 5672
    username: admin
    password: admin
#server:
#  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka #向eureka进行注册

---
spring:
  profiles: item1
server:
  port: 8101

---
spring:
  profiles: item2
server:
  port: 8102